// String should be ujique across reducers
//export const HOLIDAY_FETCHED = 'HOLIDAY_FETCHED';
export const TRADE_TYPE_SELECTED = 'TRADE_TYPE_SELECTED';
export const CURRENCY_SELECTED = 'CURRENCY_SELECTED';
export const HOLIDAY_SELECTED = 'HOLIDAY_SELECTED';
export const HOLIDAY_IN_LIST = 'HOLIDAY_IN_LIST';
export const YEAR_MONTH_SELECTED = 'YEAR_MONTH_SELECTED';
export const MONTH_SELECTED = 'MONTH_SELECTED';
export const ADD_HOLIDAY = 'ADD_HOLIDAY';
export const UNDO_ADD_HOLIDAY = 'UNDO_ADD_HOLIDAY';
export const DELETE_HOLIDAY = 'DELETE_HOLIDAY';
export const UNDO_DELETE_HOLIDAY = 'UNDO_DELETE_HOLIDAY';
export const ADD_HOLIDAY_CLICKED = 'ADD_HOLIDAYS_CLICKED';
export const DELETE_HOLIDAY_CLICKED = 'DELETE_HOLIDAYS_CLICKED';
export const RELOAD_CLICKED = 'RELOAD_CLICKED';
export const COMMIT_CHANGES = 'COMMIT_CHANGES';