export const VIEW_HOLIDAYS_MODE = 'VIEW_HOLIDAYS_MODE';
export const ADD_HOLIDAYS_MODE = 'ADD_HOLIDAYS_MODE';
export const DELETE_HOLIDAYS_MODE = 'DELETE_HOLIDAYS_MODE';
export const ADD_DELETE_HOLIDAYS_MODE = 'ADD_DELETE_HOLIDAYS_MODE';